# Generated by Django 4.0 on 2022-04-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
